name: Publish Pipeline

on:
  push:
    branches: ["main", "develop"]

jobs:
  build-jar:
    uses: firefly-oss/cicd/.github/workflows/build-maven.yaml@main
    with:
      java-version: "21"
      skip-tests: false
      jar-path: "core-banking-ledger-web/target/core-banking-ledger.jar"
    secrets:
      PAT_GITHUB_PACKAGE: ${{ secrets.PAT_GITHUB_PACKAGE }}
  docker-publish:
    needs: [build-jar]
    uses: firefly-oss/cicd/.github/workflows/docker-publish.yaml@main
    with:
      dockerfile-path: "./Dockerfile"
      image-name: "core-banking-ledger"
      docker-image-tag: "latest"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.AZURE_ACR_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.AZURE_ACR_PASSWORD }}
